Fix region exploring for Julich brain 2.4
HumanBrainProject/interactive-viewer pull request #716
Opened 2020-10-30 16:03 UTC by fsdavid

2020-10-30 18:39 UTC, xgui3783 requested changes

2020-10-30 18:39 UTC, xgui3783 commented on src/ui/parcellationRegion/region.base.spec.ts
>        kgSchema: 'fzj/mock/pr',
this is actually not what I meant.

the existing tests needs to stay,

but the logic needs to accomodate both the `region name - hemisphere` and `name` `status` scenario

2020-10-30 18:46 UTC, xgui3783 commented
I would say, just leave the PR, I can take a look at it. I think I can fix this issue.

More important is, if you can take a look at connectivity components, and see if there are any bugs

2020-10-30 18:47 UTC, fsdavid commented on src/ui/parcellationRegion/region.base.spec.ts
>        kgSchema: 'fzj/mock/pr',
actually yes, the new approach was only for working for Julich brain 2.4 I will fix it for the old version too

2020-10-30 18:53 UTC, fsdavid commented
> I would say, just leave the PR, I can take a look at it. I think I can fix this issue.
> 
> More important is, if you can take a look at connectivity components, and see if there are any bugs

I can look at both. I will fix this issue and I can already found a bug in the connectivity browser.

2020-10-31 12:35 UTC, fsdavid commented
Now both versions of julich brain should work

2020-11-02 08:37 UTC, xgui3783 commented
Thanks. 

I will add unit tests then merge

2020-11-02 09:19 UTC, merged