Fix 758 connectivity source does not have a data
HumanBrainProject/interactive-viewer pull request #776
Opened 2020-11-30 20:22 UTC by fsdavid

2020-12-01 08:20 UTC, xgui3783 requested changes
Just a minor change to variable name.

I have not tested it thoroughly, but I trust that you have.

2020-12-01 08:20 UTC, xgui3783 commented on src/services/state/viewerState/selectors.ts
> +
can you add `selector` this this variable name?

we should standardise the names in the future, but for now, all selectors should have selector in their name, same goes with action (and in the future, reducer)

2020-12-07 18:09 UTC, xgui3783 commented
@fsdavid are you still interested in this PR?

2020-12-07 18:11 UTC, fsdavid commented
> @fsdavid are you still interested in this PR?

@xgui3783 Sure, it contains important bug fixes. Thanks for reminding I will change the name now.

2020-12-07 18:22 UTC, fsdavid commented
@xgui3783 Also, I see that there are 2 conflicts, I guess you have updated "export-nehuba"? so we should use:
`"export-nehuba":` `"0.0.4",
"hbp-connectivity-component":` "^0.3.18",`

What about the second conflict, have you removed the parallel connectivity viewer for counting connected areas? There was some issue but, the current PR will fix this too. So we can include the component again.

2020-12-07 19:29 UTC, xgui3783 requested changes

2020-12-07 19:29 UTC, xgui3783 commented on src/ui/connectivityBrowser/run_test.sh
> +#! /bin/bash
This is probably not intended to be included, no?

2020-12-07 19:29 UTC, xgui3783 commented on src/ui/connectivityBrowser/test-3.sh
> +#! /bin/bash
neither is this?

2020-12-07 19:29 UTC, xgui3783 commented on src/ui/connectivityBrowser/test.sh
> +#! /bin/sh
nor this?

2020-12-07 19:31 UTC, xgui3783 commented
re: conflict, I simply move the block inside `mat-accordion` element.

2020-12-08 11:03 UTC, fsdavid commented on src/ui/connectivityBrowser/test.sh
> +#! /bin/sh
Sorry for my silly mistakes.

2020-12-08 12:49 UTC, fsdavid commented
@xgui3783 Please do not merge the PR yet. I've found one more bug which could be connected to the current branch and I will fix this first.

2020-12-08 12:53 UTC, xgui3783 commented
@fsdavid is this related to the same or different bug? if it's related to a different bug, it'd rather have two PRs addressing them

2020-12-08 17:06 UTC, fsdavid commented
@xgui3783 It is related to the same bug. So to say, the current fix caused these bugs. Now they should have been already fixed.

2020-12-08 17:09 UTC, xgui3783 commented
i am thoroughly confused... why is `SET_OVERRITEN_COLOR_MAP` needed?

2020-12-08 17:37 UTC, fsdavid commented
> SET_OVERRITEN_COLOR_MAP

`SET_OVERRITEN_COLOR_MAP` was used for connectivity visibility but the name was generalized after your comment in the last releases and now it could be used not only for connectivity. 
Why it is used? As I've already mentioned in one of the comments, the expanded connectivity accordion is not directly connected to viewing connectivity on the viewer. Accordion could be expanded but the connectivity view will not be attached in some cases. That's why we have 2 triggers in state, one for the accordion "open/close" state and the second for connectivity colors "visible/invisible" state. I don't now if with this implementation it is possible to fully remove `SET_OVERRITEN_COLOR_MAP` because `ngViewerActionClearView` was confusingly connected to pmaps and accordion "open/close" state.

2020-12-08 17:40 UTC, xgui3783 commented
@fsdavid I don't know if I follow still. do you have time for a quick zoom?

2020-12-08 17:54 UTC, fsdavid commented
@xgui3783 It is connected to #758, as before, the connectivity expansion panel "open/close" state was directly connected with viewing connectivity map on the viewer and now it is not. The bug caused more changes than was expected but it is definitely connected with #748. We could create sub-issues but I think it is not needed and even it could be incorrect. Maybe in the future, if we change the viewer so as we will remove overwritten color maps, it will not be connected to this issue, but now I think it is.

2020-12-08 17:58 UTC, xgui3783 commented
@fsdavid  it's #758  right?

also, what issue is it causing? #758 is quite clear. From what I can tell, the connectivity map is still connected with open/closing of the panel.

2020-12-08 18:09 UTC, fsdavid commented
> @fsdavid it's #758 right?
> 
> also, what issue is it causing? #758 is quite clear. From what I can tell, the connectivity map is still connected with open/closing of the panel.

@xgui3783 Sure it is #758 sorry :). So the case is that at this PR, with the first commit, I've developed more bugs :). The next commits are to fix them, not new ones. 

Yes, the panel's "open/close" state is still connected with the connectivity view (but only if the selected connectivity dataset has one). For the user, working behavior has not changed at all, but now  "open/closing" of the panel now uses "SET_CONNECTIVITY_VISIBLE". As I guess `ngViewerActionClearView`, was created for the same purposes, but for the current implementation I fix the bugs with using both `SET_CONNECTIVITY_VISIBLE` and `ngViewerActionClearView`.

2020-12-10 11:06 UTC, xgui3783 requested changes
@fsdavid thanks, just 1 final small thing re typo

2020-12-10 11:06 UTC, xgui3783 commented on src/services/state/viewerState.store.ts
> +export const SET_OVERRITEN_COLOR_MAP = `SET_OVERRITEN_COLOR_MAP`
can you corrrect typo? `SET_OVERWRITTEN_COLOR_MAP`

2020-12-10 12:14 UTC, fsdavid commented on src/services/state/viewerState.store.ts
> +export const SET_OVERRITEN_COLOR_MAP = `SET_OVERRITEN_COLOR_MAP`
Done

2020-12-10 12:20 UTC, merged

2020-12-10 12:21 UTC, xgui3783 commented
Thanks!