Add quick tour
HumanBrainProject/interactive-viewer pull request #920
Opened 2021-03-22 07:59 UTC by fsdavid

2021-03-22 08:30 UTC, xgui3783 requested changes
I think we should rethink the strategy in which we construct the quick tour.

The current method is very unmaintainable. 

Let's take a look at how `mat-menu` <https://material.angular.io/components/menu/overview> implemented the menu. 

It somewhat does exactly what we are doing, but very much extensible, and understandable.

2021-03-22 08:30 UTC, xgui3783 commented on src/ui/quickTour/quickTour.directive.ts
> +        // panelClass: ['w-100', 'h-100'],
please remove

2021-03-22 08:30 UTC, xgui3783 commented on src/ui/quickTour/quickToutCmp/quickTour.component.ts
> +  public slides: any[] = [
I think this approach is not very maintainable. 

For example, if we start to shuffling elements, we will have to recalculate the positions, and if we want to add new slides, we will have to calculate the position of those.

I think we should calculate these dynamically.

2021-03-22 08:30 UTC, xgui3783 commented on src/ui/quickTour/quickToutCmp/quickTour.component.ts
> +    this.numberOfSteps = new Array([...this.slides].filter(s => s.step).pop()['step'])
why not just use map here?

also, no need for `new Array()` constructor. `filter` and `map` already creates new copies of arrays

2021-03-22 08:30 UTC, xgui3783 commented on src/ui/quickTour/quickToutCmp/quickTour.component.ts
> +    this.observers.push(observer)
I think I see what you are trying to do here, but I think by maintaining a dynamic list of help icons, this should not be needed

2021-03-22 08:30 UTC, xgui3783 commented on src/ui/quickTour/quickToutCmp/quickTour.component.ts
> +  }
this is way too complicated and way to bespoke, and lacks maintainability.

overlapping mat drawer may be an issue, but I do not think this is the way to solve it.

2021-03-22 08:30 UTC, xgui3783 commented on src/ui/quickTour/quickToutCmp/quickTour.component.ts
> +    this.currentTip = this.slides.findIndex(s => s.step === this.slides[this.currentTip].step-1)
again, logic like this is prone to error. 

For example, we remove step 3, but step 2 and step 4 are still present.

Rather than keep the steps in property, should use linked list, which is built for use cases like this.

2021-03-22 08:30 UTC, xgui3783 commented on src/ui/quickTour/quickToutCmp/quickTour.component.ts
> +  checkSidebarStatus() {
again, this is way too complicated and unmaintainable.

2021-03-22 08:30 UTC, xgui3783 commented on src/ui/quickTour/quickToutCmp/quickTour.style.css
> +/*}*/
remove please

2021-03-22 08:30 UTC, xgui3783 commented on src/ui/quickTour/quickToutCmp/quickTour.temlate.html
> +    </svg>
hmm, I don't know if it is actually better to use a template or an actual svg for this.

2021-03-25 22:27 UTC, fsdavid commented
@xgui3783 Could you please look at the new commit? I've made some major changes after our discussion.

2021-03-26 13:19 UTC, xgui3783 requested changes
overall, much better than first approach.

Can you migrate the desc to a separate file first?

We can probably discuss how to do the overwrite position in a call in the future.

2021-03-26 13:19 UTC, xgui3783 commented on src/ui/quickTour/quickToutComponent/quickTour.component.ts
> +  }
need to check if this getter gets called in very render cycle

2021-03-26 13:19 UTC, xgui3783 commented on src/ui/quickTour/quickToutComponent/quickTour.temlate.html
> +                : '']">
this probably should be condensed into a single public property

this is not very readable.

2021-03-26 13:19 UTC, xgui3783 commented on src/ui/quickTour/quickToutComponent/quickTour.temlate.html
> +<!--                    maxWidth: slides[currentTip]?.textWidth? slides[currentTip].textWidth : null}">-->
remove please

2021-03-26 13:19 UTC, xgui3783 commented on src/ui/quickTour/quickToutComponent/quickTour.temlate.html
> +</ng-template>
probably ... we should extrapolate this into a separate component

2021-03-26 13:19 UTC, xgui3783 commented on src/ui/topMenu/topMenuCmp/topMenu.components.ts
> +    description: 'These icons provide access to plugins, pinned datasets, and user documentation. Use the profile icon to login with your EBRAINS account.',
ditto above, extrapolate into common/constants

2021-03-30 22:14 UTC, fsdavid commented on src/ui/quickTour/quickToutComponent/quickTour.component.ts
> +    this.positionChangedByArrow = false
There are some elements like `targetElWidth` which is necessary for calculations, otherwise, I've removed some.

2021-03-30 22:16 UTC, fsdavid commented on src/ui/quickTour/quickToutComponent/quickTour.component.ts
> +              setTimeout(() => this.calculateArrowPosition())
Made all the changes, but anyways `settimeout` is necessary for some slides, so I suggest keeping it.

2021-03-30 22:18 UTC, fsdavid commented on src/ui/quickTour/quickToutComponent/quickTour.component.ts
> +    if (this.tipCardEl) setTimeout(() =>this.calculatePosition(tip, width, height))
It is needed because current tip sizes are included in calculations and the tip needs to be added to the document.

2021-03-31 07:31 UTC, xgui3783 reviewed
I will take a look at the branch today, and may push some PRs to the branch, and we can discuss pros/cons

in the mean time, can you resolve the conflicts with current `dev` branch?

2021-03-31 07:31 UTC, xgui3783 commented on src/ui/quickTour/constrants.ts
> +    top?: number
why are `align`, `top` and `left` property needed?

2021-03-31 07:31 UTC, xgui3783 commented on src/ui/quickTour/constrants.ts
> +    arrow?: string
this property needs to be more explicity. `arrowType`?

2021-03-31 07:31 UTC, xgui3783 commented on src/ui/quickTour/constrants.ts
> +    arrowTransform?: string
These properties should not need necessary. 

if the `quickTourThis` directive specifies `position` attribute, these properties can and should be calculatable.

2021-03-31 07:31 UTC, xgui3783 commented on src/ui/quickTour/quickTour.service.ts
> +      this.quickTourThisDirectives.splice(i, 0, dir)
this is more complicated than it should be. I believe you really just need a `findIndex` call, then followed by a `splice` call

2021-03-31 07:31 UTC, xgui3783 commented on src/ui/quickTour/quickTour.service.ts
> +    }
I slightly disagree how this should be implemented. 

Rather than reusing `currentTip$`, I _think_ it should be a separate observable called `forceUpdate$` or `detecteChange$`,  of type `Observable<null>` and the quickTour cmp will subscribe to it. 

On emit, quickTour cmp should recalculate/rerender.

2021-03-31 07:31 UTC, xgui3783 commented on src/ui/quickTour/quickTourThis.directive.ts
> +    @Input('quick-tour-position') position: QuickTourPosition
I like this. This is much cleaner and easier to understand

2021-03-31 07:31 UTC, xgui3783 commented on src/ui/quickTour/quickToutComponent/quickTour.component.ts
> +  private leftHardcoded = false
correct me if I am missing something, but these two properties should no longer be needed?

2021-03-31 15:58 UTC, fsdavid commented on src/ui/quickTour/quickToutComponent/quickTour.component.ts
> +  private leftHardcoded = false
> correct me if I am missing something, but these two properties should no longer be needed?

I've added these properties in the last commit, they are needed because it is possible to hardcode only "top" or "left" props.

2021-03-31 16:03 UTC, fsdavid commented on src/ui/quickTour/quickTour.service.ts
> +    }
`currentTip$` - means tip object which is currently set (not only the index) Why you disagree with updating `currentTip$` when the current tip updated? is there a case that we will not need to upgrade `currentTip$` when it actually updates?

2021-03-31 16:06 UTC, fsdavid commented on src/ui/quickTour/quickTour.service.ts
> +      this.quickTourThisDirectives.splice(i, 0, dir)
Sorry did not understand what do you mean. It could be complicated on the first look, but it is quite easy logic. As I understand we change the last implementation because of the performance and this logic should be fast.

2021-03-31 16:09 UTC, xgui3783 commented on src/ui/quickTour/quickTour.service.ts
> +      this.quickTourThisDirectives.splice(i, 0, dir)
I can say that expect for `this.quickTourThisDirectives.splice(i, 0, dir)`, I did not understand the reset of the logic.

2021-03-31 16:10 UTC, fsdavid commented on src/ui/quickTour/constrants.ts
> +    top?: number
The top and left position could be hardcoded but it is not necessary because it could be attached to the element where the directive is assigned, so if the position is `top`, `align` could be `left`, `center` and `right`.

2021-03-31 16:12 UTC, fsdavid commented on src/ui/quickTour/constrants.ts
> +    arrowTransform?: string
arrow could be arount tip object, sometimes tip position is not enough to calculate arrow position

2021-03-31 16:12 UTC, xgui3783 commented on src/ui/quickTour/quickTour.service.ts
> +    }
`order` is not equivalent to and uuid, and it's dangerous to treat it so.

It's better to check for strict equivalence

2021-04-13 11:21 UTC, closed without merging